### ISSUE TITLE
Failure on arisan migrate:refresh when there are web middleware using the db

### ISSUE THREAD

**Issue by ncjoes** [recca0120/laravel-terminal#21]
I get internal server error when running artisan migrations because the request is sent as a web request, thus the pass through some middleware which are not supposed to be executed in console mode.

I suggest you find a way to switch laravel to console mode when processing requests from the terminal.

**Comment by recca0120** [comment]
You mean let $app->runningInConsole() return true ???

I think you can check route name. maybe better
