### ISSUE TITLE
Installation failed when composer install

### ISSUE THREAD

**Issue by vongola12324** [recca0120/laravel-terminal#22]
Laravel 的 framework 相依的 symfony/finder 更新到 3.3.0，雖然 framework 指定 ~3.2 但 composer 解析到 3.3.0，又 composer 無法順利移除並安裝舊版本，導致安裝錯誤。

執行記錄：
https://hastebin.com/ehujebaduc.erl

**Comment by recca0120** [comment]
好的
我更新一下

**Comment by vongola12324** [comment]
可是我使用的是 Laravel 5.4 耶，這是我 `composer why` 的結果，除了`laravel/framework`並沒有其他套件需要使用到 `symfony/finder`：
```shell
> composer why symfony/finder
laravel/framework  v5.4.24  requires  symfony/finder (~3.2)
```

且根據 [Composer 官方文件](https://getcomposer.org/doc/articles/versions.md#next-significant-release-operators) 裏面的說法：
`~3.2` 的意思是 `>=3.2 and < 4.0.0`，我推測當 `symfony/finder` 更新上去之後，因爲這個套件對`finder`的指定版本不包含3.3或以上，安裝就會失敗。

**Comment by recca0120** [comment]
將版本相依的條件做修改了
你再試看看 v1.6.11
