### ISSUE TITLE
webterminal in sub domain

### ISSUE THREAD

**Issue by loic-lopez** [recca0120/laravel-terminal#23]
Hi, how can i do if i want to access the webterminal on a sub domain ?
Thanks for reply.

**Comment by recca0120** [comment]
you don't change anything...
it will work on sub domain

**Comment by Lopez-i** [comment]
Can you improve the documentation to create a new shell command ?

**Comment by Lopez-i** [comment]
i mean how i can do if i want access the webterminal only with a sub domain ?

**Comment by recca0120** [comment]
config/terminal.php

```php
return [
    // ...
    'route' => [
        'domain' => sub.domain.com,
        'prefix' => 'terminal',
        'as' => 'terminal.',
    ]
    // ...
];
```

**Comment by Lopez-i** [comment]
Thanks, and can i apply a middleware ?

**Comment by recca0120** [comment]
yes

**Comment by Lopez-i** [comment]
Sorry but where?

**Comment by Lopez-i** [comment]
Hi , i would like to apply a permission middleware on the terminal routes
how can i do ?

**Comment by enniosousa** [comment]
> Thanks, and can i apply a middleware ?

Dont forget add `web` and `auth` middleware if you want that use do login to access

@recca0120 Could you add a similar explanation on config file

**Comment by fencermd** [comment]
Did someone applied middleware ? how and where should I do this?

**Comment by recca0120** [comment]
```
return [
    // ...
    'route' => [
        'domain' => 'sub.domain.com',
        'prefix' => 'terminal',
        'as' => 'terminal.',
        'middleware' => ['web', 'auth', 'others middleware'] // you can add middleware here
    ]
    // ...
];
```

**Comment by recca0120** [comment]
if middleware isn't work...
you need run `php artisan route:clear` to clear route cache

**Comment by fencermd** [comment]
Great, thank you.
