### ISSUE TITLE
It's not working in L 5.4

### ISSUE THREAD

**Issue by sidor555** [recca0120/laravel-terminal#25]
I have installed and followed all instructions but it not working 
Publish also had been successful
`Copied File [\vendor\recca0120\terminal\config\terminal.php] To [\config\terminal.php]
Copied Directory [\vendor\recca0120\terminal\resources\views] To [\resources\views\vendor\terminal]
Copied Directory [\vendor\recca0120\terminal\public] To [\public\vendor\terminal]
Publishing complete.` 

But no result` http://localhost/mysite/public/terminal` .. Showing 404 Page

**Comment by recca0120** [comment]
`artisan route:cache`
