### ISSUE TITLE
Document the config file

### ISSUE THREAD

**Issue by ftrotter** [recca0120/laravel-terminal#26]
It is not obvious what it means to be in the "confirmToProceed" section or what "interpreters" means. Or what "route" does. I think I can guess what the whitelist section does... but others might have trouble. and it is not clear how enabling or disabling debuging would help. 

Have read the readme, and it did not cover how to use the config file.. and the version of the config file that is listed in the readme does not match the contents of the auto-generated file.

It would help if these things were clearly explained.

**Comment by recca0120** [comment]
hello @ftrotter 
 yes I need your help ..

**Comment by pxgamer** [comment]
Perhaps this could be added to the `docs` directory, or just in [GitHub wiki][wiki].

Or I guess just added as comments to the `config/terminal.php` file, as per other Laravel config files. 👍

[wiki]: https://github.com/recca0120/laravel-terminal/wiki
