### ISSUE TITLE
Support other /vendor artisan commands

### ISSUE THREAD

**Issue by ftrotter** [recca0120/laravel-terminal#27]
We are writing our own artisan console commands, in our own name spaces. 

We successfully add them to the artisan command when we run it through the unix terminal, but they do not show up in this web terminal.

The instructions indicate that we must namespace additional commands under:

`namespace Recca0120\Terminal\Console\Commands;`

But we have good reasons for having our own namespaces for our console applications.

Perhaps we could just have a flag in our console command class called 'enable_run_through_web' or something similar which would be an indication that a command should be accessible through your app. 

Alternatively rather than an inherited class, your system could rely on classes to implement an interface of some kind? http://php.net/manual/en/language.oop5.interfaces.php

Thank you for your work a very clever approach to a common problem with Laravel.

-FT

**Comment by recca0120** [comment]
I'll add a interface to fix namespace problem.

this package support other artisan command
you can execute artisan list to check command exists or not

example
![4](https://user-images.githubusercontent.com/1390554/34031801-01e6c3f8-e1ae-11e7-8f1a-eeaa8b722981.png)

**Comment by recca0120** [comment]
Hello
I add a interface Recca0120\Terminal\Contracts\WebCommand
