### ISSUE TITLE
Unescaped Characters Displaying

### ISSUE THREAD

**Issue by benyanke** [recca0120/laravel-terminal#29]
Occasionally, I will see characters pop up which appear like they should have been escaped, but they weren't. One such example:

![image](https://user-images.githubusercontent.com/4274911/34786420-bee69b90-f5f9-11e7-863e-648399350170.png)

A very excellent tool, helpful for debugging in multiple environments.

**Comment by benyanke** [comment]
Another example, this time in tinker:

I type `use App\User;` and it comes in incorrectly.

![image](https://user-images.githubusercontent.com/4274911/34790716-428ab9d2-f608-11e7-97f0-4729df9e68db.png)

**Comment by recca0120** [comment]
@benyanke 
I'll try to fix this bug later

**Comment by benyanke** [comment]
Should also mention this is running on an amazon linux AMI (beanstalk).

**Comment by recca0120** [comment]
@benyanke 

try 1.6.19

**Comment by benyanke** [comment]
I ran `composer update recca0120/laravel-terminal` and ran `npm run dev` and it's still broken.

Is there something else needed for upgrading?

**Comment by recca0120** [comment]
try `artisan vendor:publish`

**Comment by benyanke** [comment]
That did it - thanks again.

![image](https://user-images.githubusercontent.com/4274911/37155265-131eba8c-22a8-11e8-9b2f-db549129e2f8.png)
