### ISSUE TITLE
Suggestion: Ability to select multiple MySQL connections. 

### ISSUE THREAD

**Issue by benyanke** [recca0120/laravel-terminal#31]
Currently, it seems to support only the default.

A half measure could be at least allowing to set which connection in a config file.

**Comment by recca0120** [comment]
hi @benyanke 

I add a new feature
you can chagne connection now

```bash
$ mysql
mysql> use sqlite
current: sqlite
mysql> select * from users;
```

**Comment by benyanke** [comment]
That did it - thanks again.

![image](https://user-images.githubusercontent.com/4274911/37155249-0373f372-22a8-11e8-8f2e-bfbc80b45dd8.png)
