### ISSUE TITLE
artisan vendor:publish returns 'undefinex index'

### ISSUE THREAD

**Issue by laraning** [recca0120/laravel-terminal#33]
When running it on my development server:

![image](https://user-images.githubusercontent.com/35408392/36636356-a0e6e75e-19c5-11e8-87f8-365be3e0c73b.png)

Let me know if you need more details about this error.

Thanks for the help.

**Comment by recca0120** [comment]
artisan vendor:publish will show prompt
this package cant show prompt now.

try execute `artisan vendor:publish --all`

**Comment by laraning** [comment]
thanks! Will try it out. Great work in this package :)
