### ISSUE TITLE
Js error

### ISSUE THREAD

**Issue by wagnerdracha** [recca0120/laravel-terminal#34]
Hi

My system show this error:

terminal.js:1 Uncaught (in promise) TypeError: Cannot read property 'interpreters' of undefined
    at e.<anonymous> (http://localhost/cco_teste/public/vendor/terminal/js/terminal.js:1:351778)
    at r (http://localhost/cco_teste/public/vendor/terminal/js/terminal.js:1:357549)
    at Generator._invoke (http://localhost/cco_teste/public/vendor/terminal/js/terminal.js:1:358594)
    at Generator.e.(anonymous function) [as next] (http://localhost/cco_teste/public/vendor/terminal/js/terminal.js:1:357728)
    at r (http://localhost/cco_teste/public/vendor/terminal/js/terminal.js:1:337146)
    at http://localhost/cco_teste/public/vendor/terminal/js/terminal.js:1:337292
    at new Promise (<anonymous>)
    at e.<anonymous> (http://localhost/cco_teste/public/vendor/terminal/js/terminal.js:1:337090)
    at e (http://localhost/cco_teste/public/vendor/terminal/js/terminal.js:1:351609)
    at new e (http://localhost/cco_teste/public/vendor/terminal/js/terminal.js:1:351438)

**Comment by recca0120** [comment]
Please print config/terminal.php

**Comment by wagnerdracha** [comment]
<?php

return [
    'enabled' => env('APP_DEBUG') === true,
    'whitelists' => ['127.0.0.1'],
    'route' => [
        'prefix' => 'terminal',
        'as' => 'terminal.',
        'middleware' => ['web', 'auth']
    ],
    'interpreters' => [
        'mysql' => 'mysql',
        'artisan tinker' => 'tinker',
        'tinker' => 'tinker',
    ],
    'confirmToProceed' => [
        'artisan' => [
            'migrate',
            'migrate:fresh',
            'migrate:install',
            'migrate:refresh',
            'migrate:reset',
            'migrate:rollback',
            'db:seed',
        ],
    ],
    'commands' => [
        \Recca0120\Terminal\Console\Commands\Artisan::class,
        \Recca0120\Terminal\Console\Commands\ArtisanTinker::class,
        \Recca0120\Terminal\Console\Commands\Cleanup::class,
        \Recca0120\Terminal\Console\Commands\Composer::class,
        \Recca0120\Terminal\Console\Commands\Find::class,
        \Recca0120\Terminal\Console\Commands\Mysql::class,
        \Recca0120\Terminal\Console\Commands\Tail::class,
        \Recca0120\Terminal\Console\Commands\Vi::class,
    ],
];

**Comment by recca0120** [comment]
laravel version ?

**Comment by wagnerdracha** [comment]
Laravel Framework 5.4.15

**Comment by wagnerdracha** [comment]
I need to send to view the terminal configuration??

send this:


return [
    'enabled' => env('APP_DEBUG') === true,
    'whitelists' => ['127.0.0.1'],
    'route' => [
        'prefix' => 'terminal',
        'as' => 'terminal.',
        'middleware' => ['web', 'auth']
    ],
    'interpreters' => [
        'mysql' => 'mysql',
        'artisan tinker' => 'tinker',
        'tinker' => 'tinker',
    ],
    'confirmToProceed' => [
        'artisan' => [
            'migrate',
            'migrate:fresh',
            'migrate:install',
            'migrate:refresh',
            'migrate:reset',
            'migrate:rollback',
            'db:seed',
        ],
    ],
    'commands' => [
        \Recca0120\Terminal\Console\Commands\Artisan::class,
        \Recca0120\Terminal\Console\Commands\ArtisanTinker::class,
        \Recca0120\Terminal\Console\Commands\Cleanup::class,
        \Recca0120\Terminal\Console\Commands\Composer::class,
        \Recca0120\Terminal\Console\Commands\Find::class,
        \Recca0120\Terminal\Console\Commands\Mysql::class,
        \Recca0120\Terminal\Console\Commands\Tail::class,
        \Recca0120\Terminal\Console\Commands\Vi::class,
    ],
];
