### ISSUE TITLE
Getting JSON Error

### ISSUE THREAD

**Issue by sarfraznawaz2005** [recca0120/laravel-terminal#37]
When we run our custom laravel console commands, we get following error:

**200: SyntaxError: Unexpected token E in JSON at position 0**

Can you please tell what could be wrong ?

Thanks

**Comment by recca0120** [comment]
Only this message, It`s hard to tell you where wrong is.
Can you tell me more details about your console command

**Comment by sarfraznawaz2005** [comment]
Hi, it is simple command suppossed to cleanup cache and temp files, here it is:

````
namespace Modules\Core\Console;

use Artisan;
use File;
use Illuminate\Console\Command;

class Cleanup extends Command
{
    protected $signature = 'app:cleanup';
    protected $description = 'Cleans useless data and cache files.';

    public function handle()
    {
        File::cleanDirectory(storage_path('clockwork'));
        
        Artisan::call('clear-compiled');
        Artisan::call('cache:clear');
        Artisan::call('config:clear');
        Artisan::call('view:clear');
        Artisan::call('optimize');
        Artisan::call('debugbar:clear');
    }
    
}
````

And on terminal when I type: `artisan app:cleanup`, that error comes up.

**Comment by sarfraznawaz2005** [comment]
Sorry issue was related to some more custom code on our end.

**Comment by recca0120** [comment]
it's fine
I test your code. it's working on this package ...
