### ISSUE TITLE
whitelists does not work

### ISSUE THREAD

**Issue by EmirCanSANCAR** [recca0120/laravel-terminal#41]
I'm writing 'whitelists' => ['127.0.0.1', 'my ip']
everyone reaches terminal.

**Comment by recca0120** [comment]
I'll test it

**Comment by hendeavors** [comment]
Needs to be false for whitelist to apply:

`APP_DEBUG=false`

**Comment by EmirCanSANCAR** [comment]
> Needs to be false for whitelist to apply:
> 
> `APP_DEBUG=false`

Worked. this needs to be added to the description of whitelists.

But there is something else that catches my eye. The comments regarding the enabled option writes that APP_DEBUG will work if true. but it also works when I set the value to false.

**Comment by recca0120** [comment]
you can send a pr for this issue.
thx.
