### ISSUE TITLE
Support Laravel 6

### ISSUE THREAD

**Issue by MrDreek** [recca0120/laravel-terminal#43]
Actual Behaviour
I can't upgrade to Laravel 6.0 because recca0120/laravel-terminal requires illuminate/filesystem ^5.1

Expected Behaviour
Upgrading to 6.0

Steps to Reproduce
Update laravel/framework to 6.0
composer update

**Comment by recca0120** [comment]
upgrading

**Comment by recca0120** [comment]
done.
