### ISSUE TITLE
Can't open terminal by using /terminal

### ISSUE THREAD

**Issue by PinKevin** [recca0120/laravel-terminal#73]
Hi, I have a problem when I want to use terminal in web. When I type /terminal at my app, it can't opened. Do you have any solution?

**Comment by recca0120** [comment]
have you execute this command ?
`artisan vendor:publish --provider="Recca0120\Terminal\TerminalServiceProvider"`

**Comment by PinKevin** [comment]
I'm sorry, my bad, I haven't executed that command. Now it can running succesfully, thanks.
