### ISSUE TITLE
undefined method whenCommandLifecycleIsLongerThan() - Laravel 11

### ISSUE THREAD

**Issue by mhmiton** [recca0120/laravel-terminal#77]
`Call to undefined method Recca0120\Terminal\Kernel::whenCommandLifecycleIsLongerThan()
`

Laravel: 11.11

**Comment by recca0120** [comment]
fixed

**Comment by mhmiton** [comment]
@recca0120 I updated the latest version. But, now showing this error -

`call_user_func_array(): Argument #1 ($callback) must be a valid callback, class Recca0120\Terminal\Application does not have a method "whenCommandLifecycleIsLongerThan"
`
